api_platform:
    title: 'Koalati API'
    description: 'Use Koalati''s API to integrate website testing features in your favorite tools and platforms.'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:     ['application/merge-patch+json', 'application/json']
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
    defaults:
        normalizationContext:
            groups: ['read']
        denormalizationContext:
            groups: ['write']
            allow_extra_attributes: false
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409
        Symfony\Component\Serializer\Exception\ExtraAttributesException: 400
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    openapi:
        contact:
            # The identifying name of the contact person/organization.
            name: Technologies Koalati Inc.
            # The URL pointing to the contact information. MUST be in the format of a URL.
            url: https://www.koalati.com/help-center
            # The email address of the contact person/organization. MUST be in the format of an email address.
            email: info@koalati.com
        # A URL to the Terms of Service for the API. MUST be in the format of a URL.
        termsOfService: https://www.koalati.com/terms-of-use
