framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_FROM_ADDRESS)%'
        headers:
            from: 'Koalati <%env(MAILER_FROM_ADDRESS)%>'
            X-Auto-Response-Suppress: 'OOF, DR, RN, NRN, AutoReply'
