monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        api_invalid_filters:
            type: service
            id: App\Api\Log\InvalidFilterLogHandler
        main:
            type: fingers_crossed
            action_level: error
            handler: main_group
            excluded_http_codes: [404, 405]
            channels: ["!event"]
        main_group:
            type:    group
            members: [logfile, stderr]
        logfile:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            max_files: 1
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        stderr:
            type: stream
            path: php://stderr

when@prod:
    monolog:
        handlers:
            api_invalid_filters:
                type: service
                id: App\Api\Log\InvalidFilterLogHandler
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            main_group:
                type:    group
                members: [sentry, logfile, stderr]
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::WARNING
                hub_id: Sentry\State\HubInterface
