version: "3.4"

# Production environment override
services:
  php:
    build:
      args:
        APP_ENV: prod
    environment:
      APP_ENV: prod
    extra_hosts:
      - "host.docker.internal:host-gateway"

  caddy:
    build:
      args:
        APP_ENV: prod
    environment:
      MERCURE_DEMO: # Disable the demo
      MERCURE_PUBLISHER_JWT: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT: ${MERCURE_JWT_SECRET}
