version: "3.4"

# Development environment override
services:
  php:
    build:
      args:
        APP_ENV: ${APP_ENV:-dev}
    volumes:
      - ./:/srv/app:rw,cached
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      # - ./var:/srv/app/var:rw
    environment:
      APP_ENV: ${APP_ENV:-dev}
    depends_on:
      - database
      - redis

  caddy:
    build:
      args:
        APP_ENV: ${APP_ENV:-dev}
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-ChangeMe}

  tools-service:
    image: koalati/tools-service
    depends_on:
        database:
            condition: service_healthy
    environment:
      PORT: 3000
      MOCK_API: 0
      WEBHOOK_HOST: caddy
      WEBHOOK_PATH: /webhook/test-result
      JWT_SECRET: ${TOOLS_API_JWT_SECRET:-ChangeMe123}
      AUTH_ACCESS_TOKEN: ${TOOLS_API_AUTH_ACCESS_TOKEN:-ChangeMe123}
      DATABASE_HOST: ${TOOLS_API_DATABASE_HOST:-database}
      DATABASE_NAME: ${TOOLS_API_DATABASE_NAME:-app}
      DATABASE_USER: ${TOOLS_API_DATABASE_USER:-symfony}
      DATABASE_PASSWORD: ${TOOLS_API_DATABASE_PASSWORD:-ChangeMe}
      DATABASE_REJECT_UNAUTHORIZED: 0
      PGPORT: 5432
    restart: unless-stopped
    ports:
    - 3000:3000

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT:-8080}:8080

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
###< symfony/mailer ###
