#!/bin/sh
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."

# PHPCS-fixer
echo "Running PHP-CS-fixer..."
${BASEDIR}/DEV/ci/php-cs-fixer.sh

# PHPCS-fixer
echo "Running PHPStan..."
${BASEDIR}/DEV/ci/phpstan.sh
