services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Util\Meta\MetaDriverInterface:
        alias: App\Util\Meta\Driver\MockMetaDriver

    League\Flysystem\FilesystemAdapter:
        alias: League\Flysystem\Local\LocalFilesystemAdapter

    App\Util\Screenshot\Driver\ScreenshotDriverInterface:
        alias: App\Util\Screenshot\Driver\BlankScreenshotDriver

    App\Util\Analytics\AnalyticsInterface:
        alias: App\Util\Analytics\Driver\MockDriver

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\Messenger\Exception\RecoverableMessageHandlingException
                    - Symfony\Component\Messenger\Exception\HandlerFailedException
